### ISSUE TITLE
Issues with xstyle and Win10 CTP IE 11

### ISSUE THREAD

**Issue by kelko** [kriszyp/xstyle#44]
The Internet Explorer 11 in the current Win10 CTP has a problem with xstyle which causes sites of ours to not work in that new IE.

The method "checkParser(styleSheetElement)" in css.js has the following code part

``` javascript
var parser = testElementStyle('x-parse', null, 'content');
if(parser && parser != 'none'){
    require([eval(parser)], function(parser){ ... }
}
```

The problem here is, that with the new IE the `testElementStyle` call does return neither `null` nor `'none'` but `'normal'`, which does not fit the if check but of course can't be eval-ed and thus the JavaScript engine throws an error:

```
SCRIPT5009: 'normal' is undefined
```

**Comment by onekopaka** [comment]
Changing the following line:
```javascript
if(parser && parser != 'none'){
```
to:
```javascript
if(parser && parser != 'none' && parser != 'normal'){
```
appears to have fixed things.

**Comment by paulirish** [comment]
This issue cropped up again as Chrome changed it's behavior. It just hit stable in Chrome 51 this week.

Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=609848
