### ISSUE TITLE
xstyle error during build

### ISSUE THREAD

**Issue by steveoh** [kriszyp/xstyle#45]
I believe this is related to [leaflets use](https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css#L87-L91) of [default vml](https://msdn.microsoft.com/en-us/library/ee384217%28v=vs.85%29.aspx)

> Error: Error processing CSS TypeError: Object [object Object] has no method 'extend'
>     at xstyle/core/parser.js:283:29
>     at String.replace (native)
>     at resume (xstyle/core/parser.js:282:15)
>     at parseSheet (xstyle/core/parser.js:98:4)
>     at parse (xstyle/core/parser.js:75:3)
>     at processCss (c:/Projects/GitHub/Crash-web/src/xstyle/build.js:320:2)
>     at processCss (c:/Projects/GitHub/Crash-web/src/xstyle/build/amd-css.js:144:22)
>     at processStylesheetLayers (c:/Projects/GitHub/Crash-web/src/xstyle/build/amd-css.js:38:37)
>     at Object.result.push.internStrings (c:/Projects/GitHub/Crash-web/src/xstyle/build/amd-css.js:121:7)
>     at c:/Projects/GitHub/Crash-web/src/util/build/transforms/writeAmd.js:278:30

**Comment by kriszyp** [comment]
Is this with master? Is it still happening for you? I wonder if this was due to any refactorings in master. Does it only happen with hashes inside urls?

**Comment by steveoh** [comment]
this is when using 8a80773bed850a3230451c6a38c1386e180b6070. I had to remove the leaflet css from the dojo build in order to keep going on the project. I use cssmin and create two separate files instead.

**Comment by steveoh** [comment]
I'm still getting this error and so is @stdavis on different projects. I'm using 7acb8186ccee813802625ca600eda2e307f9542c now.

**Comment by kriszyp** [comment]
I tried to doing a build with the full leaflet.css included in a stylesheet, from https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css and I still don't see any errors. Any ideas on how I can reproduce this?

**Comment by stdavis** [comment]
git clone https://github.com/agrc/ugs-chemistry
npm install && bower install
grunt esri_slurp:dev
grunt build-stage -v

Thanks for taking a look at this, Kris. We love the AMD css loader plugin
and associated build plugin that this project provides.

On Thu, Mar 19, 2015 at 10:19 PM, Kris Zyp <notifications@github.com> wrote:

> I tried to doing a build with the full leaflet.css included in a
> stylesheet, from
> https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css and I
> still don't see any errors. Any ideas on how I can reproduce this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kriszyp/xstyle/issues/45#issuecomment-83894175>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by steveoh** [comment]
I also noticed that 

https://github.com/agrc/Crash-web/blob/esri-clustering/src/app/resources/App.css#L16-L21
````css
@font-face {
  font-family: 'Ubuntu';
  font-style: normal;
  font-weight: 700;
  src: local('Ubuntu'), url(http://fonts.gstatic.com/s/ubuntu/v7/zvCUQcxqeoKhyOlbifSAaevvDin1pK8aKteLpeZ5c0A.woff2) format('woff2');
}
````

turns into 

````css
@
font - face {
````
which sorta breaks the css.

**Comment by stdavis** [comment]
Took care of the error message on my end. Thanks!

Just noticed another problem. Not sure if this is a regression or not.

before build:
```
.list-filter div[data-dojo-attach-point='buttonContainer'] .btn {
    margin: 0 5px 5px 0;
    border-radius: 15px;
    padding: 1px 8px;
}
```

after build (no space before `.btn`):
```
.list-filter div[data-dojo-attach-point='buttonContainer'].btn {
    margin: 0 5px 5px 0;
    border-radius: 15px;
    padding: 1px 8px;
}
```

I worked around this by switching the div[...] selector to use a CSS class name.
