### ISSUE TITLE
new tagged release of xstyle?

### ISSUE THREAD

**Issue by tmcgee** [kriszyp/xstyle#53]
Issue #44 is also affecting the Chrome browser in the Beta and Dev Channels at present and possibly Chrome Stable Channel very soon. Commit [7acb818](https://github.com/kriszyp/xstyle/commit/7acb8186ccee813802625ca600eda2e307f9542c) referred to in #44 solves the problem for Chrome as well on these platforms. My testing is on Windows. Others have verified it on OS-X as well.

See my post [here](https://github.com/cmv/cmv-app/issues/552) for how this effects the Configurable Map Viewer project that I am a developer for and my solution. Many other projects will be affected by this as well. My solution was to use either xstyle locally or use the latest commit in the master branch via rawcdn.

The most recent tagged release of xstyle is [v0.3.1](https://github.com/kriszyp/xstyle/releases/tag/v0.3.1) on Dec 10, 2014 was before the original issue was identified and the fix committed. Creating a new tagged release for reference via rawcdn or for download would be a desirable and more stable approach than using the latest commit in master branch. Thoughts?

**Comment by stdavis** [comment]
It's my understanding that this project is pretty much been abandoned. I would recommend transitioning off of it.

We've worked around this particular problem by pointing bower at the latest commit SHA.

In `bower.json`:
```
"xstyle": "09b4d603f63df3e7aa5acc04784e36710a75671d"
```

[Related bower docs](http://bower.io/docs/api/#install)

**Comment by tmcgee** [comment]
@stdavis thanks. I have heard that as well.

**Comment by kriszyp** [comment]
Here you go: https://github.com/kriszyp/xstyle/releases/tag/v0.3.2
Let me know if anything is missing.

**Comment by tmcgee** [comment]
@kriszyp Looks like that will work for the immediate need. thank you!
