### ISSUE TITLE
[BUG] parser is not working properly

### ISSUE THREAD

**Issue by mpajer** [kriszyp/xstyle#61]
Hello,
try to build this css:
```
input[type=radio] .classA,
input[type=checkbox] .classB {
	width: 190px;
}
```

and it produces:
`input[type=radio] .classA, input[type=checkbox].classB{width:190px;}`

Note the lack of space after input[type=checkbox], so it produces wrong css..

**Comment by adros** [comment]
Same problems occurs for :not() pseudo-selector

```
div:not(.classC) .classA,
div:not(.classC) .classB {
	width: 190px;
}
```

Produces:
```
div:not(.classC) .classA, div:not(.classC).classB{width:190px;}
```

**Comment by yangchuanlong** [comment]
meet the same problem
